"""Opt-in PostgreSQL checks; each run owns and removes only its isolated schema.

Set FEE_TEST_POSTGRES_URL to a disposable PostgreSQL database whose user may
create schemas. Existing schemas and data are never reset or migrated.
"""

import os
import secrets
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from threading import Barrier
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, event
from sqlalchemy.engine import make_url
from sqlalchemy.schema import CreateSchema, DropSchema

from fee_server.core.config import Settings
from fee_server.main import create_app

pytestmark = pytest.mark.skipif(
    not os.environ.get("FEE_TEST_POSTGRES_URL"),
    reason="Set FEE_TEST_POSTGRES_URL to run PostgreSQL migration and concurrency checks",
)

PASSWORD = "fictitious-postgres-password-123"


@pytest.fixture(scope="module")
def postgres_settings():
    source_url = make_url(os.environ["FEE_TEST_POSTGRES_URL"])
    if source_url.drivername != "postgresql+psycopg":
        pytest.fail("FEE_TEST_POSTGRES_URL must use postgresql+psycopg")
    schema_name = "fee_test_" + uuid4().hex
    engine = create_engine(source_url, hide_parameters=True)
    with engine.begin() as connection:
        connection.execute(CreateSchema(schema_name))
    database_url = source_url.update_query_dict(
        {"options": (f"-csearch_path={schema_name} -cstatement_timeout=10000 -clock_timeout=5000")}
    ).render_as_string(hide_password=False)
    secret = secrets.token_urlsafe(48)
    try:
        environment = dict(
            os.environ,
            FEE_ENVIRONMENT="test",
            FEE_DATABASE_URL=database_url,
            FEE_AUTH_SECRET_KEY=secret,
        )
        for arguments in (["upgrade", "head"], ["check"]):
            result = subprocess.run(
                [sys.executable, "-m", "alembic", *arguments],
                cwd=Path(__file__).resolve().parents[1],
                env=environment,
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )
            if result.returncode:
                output = result.stdout + result.stderr
                for value in (database_url, source_url.password, secret):
                    if value:
                        output = output.replace(value, "[redacted]")
                pytest.fail(f"Alembic {' '.join(arguments)} failed: {output}")
        yield Settings(
            environment="production",
            database_url=database_url,
            auth_secret_key=secret,
            auth_request_limit=1000,
        )
    finally:
        # The name was generated by this fixture and never comes from the URL.
        with engine.begin() as connection:
            connection.execute(DropSchema(schema_name, cascade=True))
        engine.dispose()


@pytest.fixture
def postgres_client(postgres_settings):
    with TestClient(create_app(postgres_settings)) as client:
        yield client


def register_and_login(client):
    email = f"postgres-{uuid4().hex}@example.com"
    created = client.post("/api/v1/auth/register", json={"email": email, "password": PASSWORD})
    assert created.status_code == 201
    response = client.post("/api/v1/auth/login", json={"email": email, "password": PASSWORD})
    assert response.status_code == 200
    return email, response.json()


def bearer(grant):
    return {"Authorization": "Bearer " + grant["access_token"]}


def test_postgres_migrations_support_auth_and_refresh_replay_revokes_family(postgres_client):
    email, original = register_and_login(postgres_client)
    me = postgres_client.get("/api/v1/auth/me", headers=bearer(original))
    assert me.status_code == 200
    assert me.json()["email"] == email

    refreshed = postgres_client.post(
        "/api/v1/auth/refresh", json={"refresh_token": original["refresh_token"]}
    )
    assert refreshed.status_code == 200
    replacement = refreshed.json()
    assert replacement["refresh_token"] != original["refresh_token"]
    assert replacement["session_id"] == original["session_id"]
    assert postgres_client.get("/api/v1/auth/me", headers=bearer(replacement)).status_code == 200

    replayed = postgres_client.post(
        "/api/v1/auth/refresh", json={"refresh_token": original["refresh_token"]}
    )
    assert replayed.status_code == 401
    for grant in (original, replacement):
        assert postgres_client.get("/api/v1/auth/me", headers=bearer(grant)).status_code == 401
    assert (
        postgres_client.post(
            "/api/v1/auth/refresh", json={"refresh_token": replacement["refresh_token"]}
        ).status_code
        == 401
    )


def test_postgres_concurrent_refresh_has_one_winner_then_revokes_family(
    postgres_client, postgres_settings
):
    _, original = register_and_login(postgres_client)
    barrier = Barrier(2)

    def refresh_from_independent_application():
        application = create_app(postgres_settings)
        synchronized = False

        def synchronize_session_lock(_connection, _cursor, statement, *_args):
            nonlocal synchronized
            if not synchronized and statement.startswith("UPDATE auth_sessions SET last_used_at"):
                synchronized = True
                # Both requests have read the same token before competing for
                # the session write lock. Do not block on the later token lock.
                barrier.wait(timeout=10)

        event.listen(
            application.state.database.engine, "before_cursor_execute", synchronize_session_lock
        )
        with TestClient(application) as client:
            return client.post(
                "/api/v1/auth/refresh", json={"refresh_token": original["refresh_token"]}
            )

    with ThreadPoolExecutor(max_workers=2) as executor:
        futures = [executor.submit(refresh_from_independent_application) for _ in range(2)]
        responses = [future.result(timeout=15) for future in futures]

    assert sorted(response.status_code for response in responses) == [200, 401]
    winner = next(response.json() for response in responses if response.status_code == 200)
    for grant in (original, winner):
        assert postgres_client.get("/api/v1/auth/me", headers=bearer(grant)).status_code == 401
        assert (
            postgres_client.post(
                "/api/v1/auth/refresh", json={"refresh_token": grant["refresh_token"]}
            ).status_code
            == 401
        )


def test_postgres_password_change_revokes_every_session(postgres_client):
    email, original = register_and_login(postgres_client)
    second_login = postgres_client.post(
        "/api/v1/auth/login", json={"email": email, "password": PASSWORD}
    )
    assert second_login.status_code == 200
    second_session = second_login.json()
    new_password = "replacement-postgres-password-456"
    changed = postgres_client.post(
        "/api/v1/auth/change-password",
        headers=bearer(original),
        json={"current_password": PASSWORD, "new_password": new_password},
    )

    assert changed.status_code == 204
    for grant in (original, second_session):
        assert postgres_client.get("/api/v1/auth/me", headers=bearer(grant)).status_code == 401
        assert (
            postgres_client.post(
                "/api/v1/auth/refresh", json={"refresh_token": grant["refresh_token"]}
            ).status_code
            == 401
        )
    assert (
        postgres_client.post(
            "/api/v1/auth/login", json={"email": email, "password": PASSWORD}
        ).status_code
        == 401
    )
    assert (
        postgres_client.post(
            "/api/v1/auth/login", json={"email": email, "password": new_password}
        ).status_code
        == 200
    )
